# conda env create --file environment.yml
# mamba env create --file environment.yml
name: riesgos
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fs
  - jupyter
  - jupyterlab
  - markupsafe=2.0.1
  - pathlib
  - pip
  - pyprojroot
  - pip:
    - pyhere
  - numpy 
  - pandas
  - matplotlib
  - seaborn
  